### ISSUE TITLE
Change license to BSD or ISC or Unlicense

### ISSUE THREAD

**Issue by wdlkmpx** [wdlkmpx/gmrun#2]
The project has been mostly rewritten, it has been converted to C.

Permissive licenses are the rage now, so it's time to follow suit. `history.,c/h config_prefs.c/.h` are under the `unlicense` license.

`main.c / gtkcompletionline.c` are under the GPL2 license, those files were mostly rewritten. But I can't change the license without the original author's permission.

So I ask @mishoo permission to change the license to BSD or ISC or unlicense, whatever license he prefers.

Text:
`I agree to relicense the GMRUN project to <license>`

**Comment by mishoo** [comment]
Warms my heart that this code that I've written in another life is still being used and maintained. :)

I agree to change the license, let's go with ISC.

**Comment by wdlkmpx** [comment]
Thanks, I'll change it.

gmrun is my favorite app launcher, the only one I use since 2015 perhaps.

So I decided to try to fix some issues. I started by updating the build system, then some fixes here and there.

There is another gmrun repo with a different codebase at gitlab with gtk3 support, I tried to integrate everything but my version was too different, I only took parts that were that were heavily changed, in the end it's been basically me.

This repo is the closest to the old gmrun with the option to use GLib's freedesktop handling, with several memory leaks and buggy code identified and fixed, I added many fixes in the last months, it has proper gtk3 support.

I plan to add gtk4 support, early tests show that gmrun crashes with GtkApplication code, so who knows-

So overall, this is the less buggy gmrun, you might to make the sourceforge project point to this repo, I can also give you write access hehe..

**Comment by mishoo** [comment]
I use it since 2001, of course :)  Looks like in Arch Linux, at least, the upstream is your repository — thanks for maintaining it!

I did notice a few issues lately, but I completely lost interest in hacking C/C++, it's just good enough for me..  I don't know why I can't get it off my fingers, could be the Ctrl-R history search, no other launcher seems to have it.

**Comment by wdlkmpx** [comment]
Well, version 1.0w will be a good version. I learned a lot about GTK and GLIB this year.

This repo is only the upstream in Arch Linux and Slackware (slackbuilds), all the other distros use the SF one with some patches.

Overall the `old` gmrun works ok with GTK2 only, it has the history search broken or buggy (!/ CTRL-S) I think, only the reverse search works (mostly) fine, but a bit buggy [CTRL-R].

In `0.9.5w` the history search is even more broken, and lacks the geometry option, gmrun doesn't notify when you enter an invalid command, it just closes the window.

The `next version (1.0w)` fixes a number of issues, reintroduces the geometry option, adds gtk3 support, glib url/file handling (freedesktop), desktop file, icon, manual.1.

I could not fix the ! command, so I removed it, the CTRL-S/R have been reimplemented to only match the start of the string, and I'm yet to reimplement the "advance" flag, that flag was also broken. Overall gtkcompletionline.c has been simplified.

**Comment by mishoo** [comment]
> the CTRL-S/R have been reimplemented to only match the start of the string

Not sure I like this, if I understand it correctly.  In bash it matches anywhere on a history line.  For example (and I really do use this) I type `Ctrl-R p r o f` to bring this history line: `firefox --profilemanager --no-remote`.  Will this no longer work?

**Comment by wdlkmpx** [comment]
You're right, I just tested and it matches anywhere on strings.
I use bash everyday, but for some reason I never used the search history feature.

Commit https://github.com/wdlkmpx/gmrun/commit/48c9f0c10a0c42c87f2a7ea19a09915079e5feed 
partially restores the old behavior of CTRL-S/CTRL-R

![Screenshot(6)](https://user-images.githubusercontent.com/10052849/95386643-30f78d00-0922-11eb-98f0-15b7e4239ab1.png)

The advance flag is a plus that will take some time to reimplement.

I got quite confused while trying to understand the search history, 'cause it was partially broken for newer distros and I was expecting something different, I only used UP/DOWN to find the correct item.

**Comment by wdlkmpx** [comment]
Ok I think the bash-like search is fixed
Commit https://github.com/wdlkmpx/gmrun/commit/177832c04a11d99b9eb0928fe7ee4fa93e982cc1
reimplements the old behavior, details in the commit msg

But gmrun supported using the entry text as the first search text, bash does not support that, it ignores the current text in the terminal, you have to type something after entering the search mode.

That's why I'm not adding this code...
```diff
diff --git a/src/gtkcompletionline.c b/src/gtkcompletionline.c
index 8acf25f..6cb1bde 100644
--- a/src/gtkcompletionline.c
+++ b/src/gtkcompletionline.c
@@ -1028,10 +1028,18 @@ on_key_press(GtkCompletionLine *cl, GdkEventKey *event, gpointer data)
                }
             }
             if (cl->hist_search_mode == FALSE) {
+               char * entry_text = strdup (gtk_entry_get_text (GTK_ENTRY (cl)));
                gtk_entry_set_text (GTK_ENTRY (cl), "");
                cl->hist_search_mode = TRUE;
                cl->hist_word[0] = 0;
                cl->hist_word_count = 0;
+               if (*entry_text) {
+                  // use stored (non-empty) entry text as the first search text
+                  strncpy (cl->hist_word, entry_text, sizeof(cl->hist_word));
+                  cl->hist_word_count = strlen (cl->hist_word);
+                  search_history (cl, 0);
+               }
+               free (entry_text);
                g_signal_emit_by_name(G_OBJECT(cl), "search_mode");
             } else {
                // search next result for `cl->hist_word`
```

**Comment by wdlkmpx** [comment]
I kind of understand why you abandoned c++, it's too complex and almost undebuggable. C has a clean and elegant syntax, but it's too primitive, it takes months to achieve simple things. But it's about personality traits: masochism.

I'm sure you'll like 1.0w, I reimplemented "!" in a more flexible way https://github.com/wdlkmpx/gmrun/commit/68282dd4c0e88bbb3006e935a99514ed27f371d4
(also fixed an issue from previous commit)

Overall it's feature-complete again, but I might have removed something people use: ctrl-g / ctrl-e 

I might add an option to make it look like a traditional app launcher, like the Windows one, so that it becomes more popular.
