### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by jrollins** [wdlkmpx/gmrun#20]
I would really like to run gmrun under wayland.  Is there a path for supporting wayland in gmrun?  maybe gtk4?

**Comment by gen2brain** [comment]
What is wrong with gtk 3 and wayland?

**Comment by jrollins** [comment]
Oh I don't know, I guess I wasn't aware the gtk3 supported wayland.  Does gmrun support wayland currently?  I'm running a pure wayland system and when I try to launche gmrun I get:
```
servo:~ 0$ gmrun
(gmrun:138263): Gtk-WARNING **: 09:56:28.297: cannot open display: 
servo:~ 1$ 
```
What do I need to do to get it to work with wayland?  I'm running debian trixie/sid.

**Comment by gen2brain** [comment]
Gmrun should not care about Wayland, it already use the toolkit. I use it
on labwc, and even if it does not work it should fallback to X11, you have
other issues.

**Comment by jrollins** [comment]
gmrun in debian does not work on wayland, so I'm trying to figure out what the issue is.  If you think upstream supports wayland that's great, I'll try to figure out what's wrong with the debian packages.

I'm not interested in running X anymore, so I'm not running Xwayland.

**Comment by jrollins** [comment]
FYI I recompiled the latest upstream with gtk3 and it works fine on my wayland system.  I will help get the debian package recompiled against gtk3 as well.  Thanks for the patience and feedback.
