### ISSUE TITLE
regressions in switching from system(3) to g_shell_parse_argv() / g_spawn_async()

### ISSUE THREAD

**Issue by zgrim** [wdlkmpx/gmrun#4]
In 3d3c2785edae3e8881579347add1561875b597d5 the plain system(3) was changed to a g_shell_parse_argv() and g_spawn_async() combo, which unfortunately has reduced the capabilities of the app.

For example, one could previously specify env vars for the child process, e.g. "FOO=1 BAR=2 /path/to/app". This now errors out with "Failed to execute child process "FOO=1", whereas it would previously run ok.
Or e.g. "for i in $(seq 3) ; do xterm & done" would previously spawn 3 xterms, and now fails to execute. Same for pipes, subprocesses, etc, IMHO it's pretty obvious the plain system(3) call is a bit more useful, I'd argue it's the most important purpose of the app. :)

Please revert this, if possible, as it's already made its way in distros (Arch) and broke my flow :)
Thanks!

**Comment by wdlkmpx** [comment]
It's interesting, some people consider the history search the most important feature (CTRL-R / CTRL-S / !) and that was completely broken in 0.9.5w.. but it was also somewhat broken in the old gmrun.

The new behavior relies on glib2 to produce meaningful error messages.. but as you can see, it is limiting what you can do, the shell stuff.

I've never even considered providing full shell commands to gmrun, it never crossed my mind, but it looks interesting.

I'll see what I can do to bring back the old system() call as an option... probably the default option.

Now talking about glib, tthis new version has an option to use freedesktop stuff ignoring the url / file handlers in /etc/gmrunrc ... take a look at the config and see for yourself ...

**Comment by wdlkmpx** [comment]
This issue is fixed, but I guess I should tweak or fix more things before releasing a new version ... suggestions are welcome

**Comment by zgrim** [comment]
Great! Thank you very much, awesome job!
Thanks for maintaining this gem too, btw. :)
